# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!

target 'Boring' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!

    pod 'WMPageController'
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'UIColor-HexRGB'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'Toast'
    
end
